extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:prettier/recommended
plugins:
  - promise
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  node: true
  es6: true
rules:
  import/no-unresolved:
    - error
    - commonjs: true
  import/no-absolute-path:
    - error
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
  no-console:
    - off
  promise/always-return:
    - error
  promise/catch-or-return:
    - error
  promise/no-nesting:
    - warn
