extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 6
  sourceType: module
env:
  node: true
  es6: true
rules:
  import/no-unresolved:
    - error
    - commonjs: true
  import/no-absolute-path:
    - error
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
  no-console:
    - off
