extends: airbnb
parser: babel-eslint
ecmaFeatures:
  classes: true
  jsx: true
settings:
  import/resolver:
    webpack:
      config:
        resolve:
          modules:
            - src
          extensions:
            - .js
            - .jsx
            - .json
            - .react.js
rules:
  quote-props:
    - error
    - as-needed
    - unnecessary: true
      numbers: true
      keywords: true
  no-unused-expressions:
    - error
    - allowTaggedTemplates: true
  jsx-a11y/heading-has-content: false
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
      - ./webpack/**
