extends:
  - fbjs
  - plugin:prettier/recommended
  - prettier/react
plugins:
  - prettier
  - react
parser:
  babel-eslint
rules:
  relay/graphql-naming: 0
  max-len: 0
env:
  node: true
  browser: true
