version: '3'
services:
  app:
    container_name: app
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongo
      - MONGO_PORT=27017
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - "27017:27017"
