version: 2

jobs:
  setup:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install packages
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  checks:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - run:
          name: Lint code
          command: yarn lint


  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - run:
          name: Build artifacts
          command: yarn build

      - store_artifacts:
          path: dist


  deploy:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/repo
    steps:
      - deploy:
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN


workflows:
  version: 2
  # The main workflow tests PR's and deploys master
  main:
    jobs:
      - setup
      - checks:
          requires:
            - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - setup
            - build
          filters:
            branches:
              only: master
