version: 2
jobs:
  check:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: Install packages
        command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Lint code
        command: yarn lint


  deploy:
    docker:
      - image: circleci/node:10.13

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: Install packages
        command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
        name: Build static files
        command: yarn build

      - run:
        name: Deploy to Firebase
        command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN


workflows:
  version: 2

  - "Deploy master":
    jobs:
      - check
      - deploy:
          filters:
            branches:
              only: master
              
  - "Pull request checks":
    jobs:
      - check
